### ISSUE TITLE
Layout margins issues

### ISSUE THREAD

**Issue by julasamer** [getwagit/Baya#66]
I don't understand how to use layout margins, or they don't seem to work.

For example, given two UIViews, one inside the other, do `subview.layoutWithMargins(bayaMargins: UIEdgeInsetsMake(10, 10, 10, 10))`. The result is that the subview matches the parent's size instead of having a 10pt margin. 

Stepping through the layouting code, there is nothing that would apply the margin - it just applies the frame with which I called `layoutWith` to the subview.

I managed to "fix" the problem, but I'm pretty sure it's not the intended way:

In BayaMarginsLayout, I changed the `layoutWith(frame:)` method to `element.layoutWith(frame: UIEdgeInsetsInsetRect(frame, bayaMargins))`.

But this didn't work well with `BayaFrameLayout`, where I removed the code applying margins - it caused the margins to be applied twice. I'm not sure about other layouts, but for me, it seems to work fine now.

**Comment by julasamer** [comment]
Figured out my problem: I'm supposed to call `startLayout(with:)`, not `layout(with:)`. 

This happened due to a problem in the "Basic Usage" section, though:
It tells me that I should declare the layout as `var layout: BayaLayoutable?`, and then tells me to call `layout?.startLayout(with: view.bounds)` later on. 

But this causes the error `Value of type 'BayaLayoutable' has no member 'startLayout'`. So I checked for other methods, and `layoutWith(frame:)` did something quite close to what I wanted. 

The fix is: declare the layout as `var layout: BayaLayout?`, then it's actually possible to call `startLayout`.

**Comment by marcorei** [comment]
Heh. I forgot to update that part of the Readme when we updated the api. I'm sorry that you had to figure it out that way! Will be updated!

***

The responsibility of handling the margins lies with the parent layout. That's why the margins are lost when calling `layoutWith(frame:)` directly.

`startLayout(with:)` takes care about margins, `.matchParent` or `.wrapContent` modes and initial measurement.

**Comment by marcorei** [comment]
Fixed! Thanks for the issue!
